### PR TITLE
Use separate MetaPhysicL

### PR DESCRIPTION
**Pull request by roystgnr**
Now that https://github.com/roystgnr/MetaPhysicL/ is public, we don't need to keep a copy of a subset of it here.

This gets us away from the outdated fork we were using, hopefully fixes the bugs we found there, and should avoid letting us get out of date again in the future.  I've tested both with and without MetaPhysicL enabled.

### CODE REVIEW

**Comment by roystgnr** [comment]
Clark reports that this is now building for him, so I'll merge shortly unless @nicholasmalaya objects.

It doesn't yet fix the error he's getting from MetaPhysicL, but now we ought to be able to fix that upstream at least.

**Comment by nicholasmalaya** [comment]
Let me take a look at it, I actually have some free time! I'll definitely go over it before Monday, unless you need it sooner.

**Comment by nicholasmalaya** [comment]
Honestly this looks great. Thanks very much @roystgnr. My only comment is: can you add a bullet to the changelog? 

This is a sufficiently significant update that I'm inclined to roll a MASA released for it. We can discuss that after merging this ticket in a separate piece of work.

**Comment by roystgnr** [comment]
Let me finish tracking down the bug that @clarkpede found via https://github.com/roystgnr/MASA/pull/1, then I'll add a changelog bullet, then yeah, we definitely should tag and release.

In theory the bugfix should be solely within https://github.com/roystgnr/MetaPhysicL and this branch will just be correct after that's done, but I want to be sure of that before we get too excited.

I was hoping to have this all finished by now but I think I've got a sinus infection and I've gotten almost nothing done so far today.

**Comment by nicholasmalaya** [comment]
No rush on my account, let me know if I can help with the bug-hunt.

**Pull request merged**
