### PR TITLE
Adding Incomp NS with Boussinesq Bouyancy Solution

### PR DESCRIPTION
**Pull request by jamelvin**
This is the addition of a new solution for the incomp Navier-Stokes with a Boussinesq Buoyancy.  At this stage the gravity is assumed to be in the y-direction, but that can easily be generalized going forward.  This has been tested and verified and successfully used to verify a stratified homogeneous solution in PoongBack.  Let me know if you need documentation for the formulation or have any questions.  Thanks.

### CODE REVIEW

**Comment by roystgnr** [comment]
The final version of the code looks good, thanks!  We could merge as-is, but IMHO you should squash the whole branch down to a single commit before we merge.

I love having as many commits as possible when the series looks like "add feature A, add feature B, add feature C, now make A compatible with D, now add D", especially if those intermediate commits were successfully tested against internal or external apps, but if the series looks like "add feature A-broken, now fix some of it to get A-less-broken, now fix more to get A-slightly-broken" then those intermediate checkpoints aren't useful.

**Comment by nicholasmalaya** [comment]
Few things: 

1) Please add a bullet to the CHANGELOG noting the addition of this MMS
2) Please add yourself to the AUTHORS file
3) My principle concern is the lack of a verification test. I really would like something that instantiates and tests this functionality. 

4) I'm not sure this handles the optional metaphysicl in a manner we want. Probably worth a dialogue. Some of this applies to @roystgnr. If I'm reading this correctly, these routines are always being compiled, but with an ifdef that comments everything out if metaphyscl is not defined. 

I would rather we optionally compile the AD files if metaphysicl is defined by the build system.

**Comment by roystgnr** [comment]
The first three concerns are reasonable.  But switching around the conditional compilation scheme shouldn't be mixed into this PR; that was my bad and I should end up fixing it eventually.

**Comment by nicholasmalaya** [comment]
Roy, I do agree that this is probably most appropriate as a separate PR. I wanted to check that this sounded like a reasonable approach. 

@jamelvin -- one other thing came to mind. We like to use doxygen or LaTeX to document what the solution MMS form takes. Is this something you have? If so, I'd like to push that either into the source or at: https://github.com/manufactured-solutions/analytical (can be a separate PR) so that users can look at documentation about what the model form of this solution is. Hope that makes sense.

If we can get that and the first three bullets (as well as Roy's separate concern) addressed, this should only require a cursory review before merge. 

Thank you for the contribution! This should be a very valuable MMS to have, and if we can get everything included before July 6th, I'll be sure to highlight it during my MASA talk at LANL.

**Comment by roystgnr** [comment]
Ceasing to compile code that's all ifdef'ed out would be an improvement, yes.  I probably patterned the current setup on libMesh, where we have a number of files that basically become empty when their corresponding configuration options aren't set.  In libMesh that actually makes sense, because we have a shell script to automatically add all new source files to Makefile.am and that script only works if we can treat them equally.  In MASA we're hand-editing Makefile.am so we might as well take advantage of the extra flexibility that gives us.

As long as we're talking about future PRs inspired by this one: I almost slagged Jeremy for using third derivatives in a PDE that should only need second derivatives, only to look into MASA and realize that he was just copying *my* use of third derivatives in PDEs that should only need second derivatives.  After this is finished and merged I'll look at changing that, which should provide a negligible performance improvement as well as a significant less-confusing-code improvement.

**Comment by jamelvin** [comment]
Okay thanks, sounds good guys.

I have a latex document with the formulation that I will look at merging into the current documentation and I will look into adding the verification test and applying the other changes requested.  Let me know if anything else comes to mind.

**Comment by nicholasmalaya** [comment]
I wanted to ping @jamelvin and @roystgnr to see if we are still waiting on some updates to merge this fellow?

**Comment by roystgnr** [comment]
Just CHANGELOG and AUTHORS fixes are critical, and those are easy enough for one of us to do if @jamelvin is buried with other things.  I'd been waiting on "look into the verification test" but if that's not going to happen soon then it's not worth holding up the merge for.

**Comment by jamelvin** [comment]
My bad guys, I forgot about this.  I will make those changes and see if the
verification test is a quick addition or not.  I'll get back to you guys
tomorrow on that.

Jeremy

**Comment by jamelvin** [comment]
Okay, I think I made all the requested changes and I added a cpp test to the tests folder (using ad_ins.cpp as a template).  I assume this is what you were driving at?  If not, let me know and I can change that.

I still have to merge in my documentation, but I think that can wait for a second pull request.  Let me know if you think I should make any more changes.  Thanks!

**Comment by roystgnr** [comment]
:+1: once Nick's happy.

**Comment by nicholasmalaya** [comment]
All tests passing on my boxes:

<pre>
-------------------------------------------------------
Initializing AD MASA Tests
-------------------------------------------------------
PASS: ad_init.sh
PASS: ad_euler
PASS: ad_cns
Shadow relative error = 3.92051e-15
Shadow relative error = 3.92051e-15
Shadow relative error = 1.62548e-14
Shadow relative error = 1.62548e-14
PASS: ad_ins
Shadow relative error = 2.60845e-15
Shadow relative error = 2.60845e-15
Shadow relative error = 2.60845e-15
Shadow relative error = 2.60845e-15
PASS: ad_cns_crossterm
PASS: ad_divgradsimple
Shadow relative error = 2.94779e-15
Shadow relative error = 3.47685e-15
Shadow relative error = 3.07533e-15
Shadow relative error = 4.51488e-15
Shadow relative error = 2.42777e-15
Shadow relative error = 3.08434e-14
PASS: ns3d_incompbouss
</pre>

:100: 

Thanks for your contribution!

**Pull request merged**
