### PR TITLE
Fixed convective terms (sign error) in the Navier-Stokes AD solution and the AD example.

### PR DESCRIPTION
**Pull request by clarkpede**
There was an inconsistency between the navierstokes_3d_incompressible manufactured solution and the navierstokes_3d_incompressible_homogeneous manufactured solution.  I corrected the convective terms to be negative, which matches the signs of the pressure and viscous terms.  This correction is also consistent with the derivation of a manufactured solution.

### CODE REVIEW

**Comment by nicholasmalaya** [comment]
Please add a bullet to the CHANGELOG in MASA detailing this change. 

(I'm being picky)

**Comment by nicholasmalaya** [comment]
Another general comment: this pull request is coming from your master branch. Typically you want to create a branch inside your Clark fork of masa, that might be called ad_sign_fix, for instance. Good habit to get into. 

This is useful because it permits you simultaneously work on several changes in parallel. This also prevents checking in unstable code to master, even if it 'just' your master branch.

**Comment by clarkpede** [comment]
Thanks for the advice.  I just added to the changelog.

**Comment by roystgnr** [comment]
:+1:, thanks!

**Comment by nicholasmalaya** [comment]
:+1: -- also looks good to me. Thanks for doing this!

**Pull request merged**
